# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"). You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2021 David Stes
#

Vagrant.configure("2") do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "openindiana/hipster"

    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    config.vm.box_check_update = true

    # Forward X11 to run the Smalltalk GUI on the host
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true

    # Install the Cog-Spur VM and git clone the Cuis images
    config.vm.provision "shell", inline: <<-SHELL
        echo "Changing Cog Spur and VectorEnginePlugin version-lock facets"

# unlock version-lock to try to install the most recent (compatible) version
# that is still compatible with the base OI box without updating the OS
# by updating the OI box (full OS pkg update) may still give a more recent VM

	pfexec pkg change-facet \
	  facet.version-lock.runtime/smalltalk/cog-spur=false \
	  facet.version-lock.runtime/smalltalk/cog-spur-display-X11=false \
	  facet.version-lock.runtime/smalltalk/cog-spur-nodisplay=false \
	  facet.version-lock.runtime/smalltalk/cog-spur-ssl=false \
	  facet.version-lock.runtime/smalltalk/cog-spur-vep=false

        echo "Installing Cog Spur and VectorEnginePlugin"
        pfexec pkg install git \
		runtime/smalltalk/cog-spur runtime/smalltalk/cog-spur-vep

#	Squeak Cog Spur requires proc_priocntl or prints a warning
	echo "Adding PRIV_DEFAULT=basic,proc_priocntl to policy.conf"
	cp /etc/security/policy.conf /etc/security/policy.conf.$(date +"%F")
	echo "PRIV_DEFAULT=basic,proc_priocntl" >> /etc/security/policy.conf

        echo "Setup script to clone Cuis"
        echo 'git clone https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev.git' >> clone-cuis.sh
        echo "Setup script to clone DrGeo"
	echo 'git clone https://github.com/hilaire/cuis-xp.git' >> clone-drgeo.sh

        echo "End of Cuis install"
        echo "Run DrGeo on Cuis by logging in (vagrant ssh)"
	echo "Then run: sh ./clone-cuis.sh"
	echo "Then run: sh ./clone-drgeo.sh"
	echo "cd Cuis-Smalltalk-Dev.git"
	echo "squeak Cuis5.0-<nn>.image"
	echo "In Cuis, fileIn DrGeo.pck.st"
	echo "In a Cuis workspace run: DrGeoSystem beDevelopment"
    SHELL

end

