# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"). You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2021 David Stes
#

Vagrant.configure("2") do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "openindiana/hipster"

    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    config.vm.box_check_update = true

    # Forward X11 to run GUI on the host
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true

    config.vm.provision "shell", inline: <<-SHELL

        echo "Test whether the latex profile exists"
	test -f /vagrant/texlive.profile || exit -1

        echo "Download install-tl"
        pfexec wget -q -O install-tl-unx.tar.gz http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz

        echo "Extract install-tl"
# could also --strip-components 1 -C install-tl-unx
	pfexec gtar xfz install-tl-unx.tar.gz || exit -1

# the install-tl script is in a directory that changes name every day
	INSTALLTL=`find . -name install-tl -perm 755 -type f`
	pfexec $INSTALLTL -profile /vagrant/texlive.profile
    SHELL

end

