# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"). You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2021 David Stes
#

Vagrant.configure("2") do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "openindiana/hipster"

    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    config.vm.box_check_update = true

    # mkdocs serve listens on 127.0.0.1:8000 in the guest,
    # forward to 127.0.0.1:8000 on the host
    config.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true

    # for more info see
    # http://docs.openindiana.org/contrib/getting-started/

    config.vm.provision "shell", inline: <<-SHELL

	# there used to be a futures package in the repo ...
	# library/python/futures seems to have a problem now
        pfexec pkg install -v \
		git lynx links\
		library/python/futures \
		library/python/mkdocs \
		developer/documentation-tool/mdl

	# as of 21/9/2021 futures IPS is missing so install by pip
	pfexec pip install futures

        echo "Run mkdocs by logging in (vagrant ssh)"
	echo ""
	echo "Then run: git clone https://github.com/OpenIndiana/oi-docs.git"
	echo "Then do:  cd oi-docs;mdl -s markdownlint-rules.rb ."
	echo "Start a webserver: mkdocs serve -a 0.0.0.0:8000"
	echo "Preview with the lynx or links web browers in the guest"
	echo "Or try to connect to http://127.0.0.1:8000 on the host"
	echo ""
        echo "More info at http://docs.openindiana.org/contrib/getting-started/"
    SHELL

end

